export const CLEAR_BOOKING_SUCCESS = "CLEAR_BOOKING_SUCCESS";
export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS";
export const REMOVE_BOOKING_SUCCESS = "REMOVE_BOOKING_SUCCESS";
export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS"
export const LOAD_ASYNCDATA_SUCCESS = "LOAD_ASYNCDATA_SUCCESS";

export const LOAD_APP_SETTING_SUCCESS = "LOAD_APP_SETTING_SUCCESS";
export const LOAD_APP_NOTIFICATION_SUCCESS = "LOAD_APP_NOTIFICATION_SUCCESS";
export const LOAD_DETAILS_SUCCESS = "LOAD_DETAILS_SUCCESS";
export const LOAD_STAFF_SUCCESS = "LOAD_STAFF_SUCCESS";
export const LOAD_GALLERY_SUCCESS = "LOAD_GALLERY_SUCCESS";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS";
export const LOAD_GALLERY_MAPPING_SUCCESS = "LOAD_GALLERY_MAPPING_SUCCESS";

// BUSINESS LOCATIONS
export const LOAD_BUSINESS_LOCATION_SUCCESS = "LOAD_BUSINESS_LOCATION_SUCCESS";

export const LOAD_BUSINESS_LOCATION_STAFF_MAP_SUCCESS = "LOAD_BUSINESS_LOCATION_STAFF_MAP_SUCCESS";

// WAIT LIST
export const LOAD_WAIT_LIST_SUCCESS = "LOAD_WAIT_LIST_SUCCESS";
export const ADD_WAIT_LIST_SUCCESS = "ADD_WAIT_LIST_SUCCESS";
export const DELETE_WAIT_LIST_SUCCESS = "DELETE_WAIT_LIST_SUCCESS";

//INTERNAL CALLS
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const END_AJAX_CALL = "END_AJAX_CALL";
export const ERROR_AJAX_CALL = "ERROR_AJAX_CALL";

//PAYMENTS
export const PAYMENT_STATUS_SUCCESS = "PAYMENT_STATUS_SUCCESS";

// SERVICE DATA
export const LOAD_SERVICE_CATEGORY_SUCCESS = "LOAD_SERVICE_CATEGORY_SUCCESS";
export const LOAD_SERVICE_SUCCESS = "LOAD_SERVICE_SUCCESS";
export const LOAD_SERVICE_DETAIL_SUCCESS = "LOAD_SERVICE_DETAIL_SUCCESS";
export const LOAD_SERVICE_STAFF_MAP_SUCCESS = "LOAD_SERVICE_STAFF_MAP_SUCCESS";
export const LOAD_SERVICE_BUSINESS_LOCATION_MAP_SUCCESS = "LOAD_SERVICE_BUSINESS_LOCATION_MAP_SUCCESS";